(function(){
"use strict";
const STORE_KEY="jr_sesau_card_return_v2";
function uuid(){if(window.crypto&&crypto.randomUUID)return crypto.randomUUID();const b=new Uint8Array(16);crypto.getRandomValues(b);b[6]=(b[6]&15)|64;b[8]=(b[8]&63)|128;const h=Array.from(b,x=>x.toString(16).padStart(2,"0")).join("");return h.slice(0,8)+"-"+h.slice(8,12)+"-"+h.slice(12,16)+"-"+h.slice(16,20)+"-"+h.slice(20);}
let errorTimer;
function showError(message){clearTimeout(errorTimer);const box=document.getElementById("checkoutError");if(box){box.textContent=message||"Não foi possível continuar agora.";box.hidden=false;errorTimer=setTimeout(()=>{box.hidden=true;},15000);box.scrollIntoView({behavior:"smooth",block:"center"});}}
function openPlatform(accessToken,platformUrl){if(!accessToken||!platformUrl)return showError("A liberação do acesso não foi retornada.");const form=document.createElement("form");form.method="POST";form.action=String(platformUrl).replace(/\/$/,"")+"/api/purchase-entry";form.style.display="none";const input=document.createElement("input");input.type="hidden";input.name="token";input.value=accessToken;form.appendChild(input);document.body.appendChild(form);form.submit();}
function selectedArea(){return document.querySelector('input[name="area"]:checked')?.value||"";}
function selectedVariant(){return document.querySelector('input[name="area"]:checked')?.dataset.variant||"";}
function cleanReturnUrl(){try{const u=new URL(window.location.href);["card_return","t","payment_id","collection_id","status","collection_status","external_reference","preference_id","merchant_order_id","payment_type"].forEach(k=>u.searchParams.delete(k));history.replaceState(null,"",u.pathname+(u.searchParams.toString()?"?"+u.searchParams.toString():"")+u.hash);}catch{}}
async function verifyCard(checkoutToken,paymentId){const response=await fetch("/api/payment-status",{method:"POST",headers:{"Content-Type":"application/json"},cache:"no-store",body:JSON.stringify({checkoutToken,paymentId})});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(typeof data.error==="string"?data.error:"Não foi possível confirmar o cartão.");return data;}
async function handleReturn(){try{const pending=JSON.parse(localStorage.getItem("jr_sesau_infinitepay_v1")||"null");if(new URL(location.href).searchParams.has("infinite_return")||(pending&&Date.now()-Number(pending.createdAt||0)<24*60*60*1000))return;}catch{}const u=new URL(window.location.href);const explicitReturn=u.searchParams.has("t")||u.searchParams.has("payment_id")||u.searchParams.has("collection_id");let checkoutToken=u.searchParams.get("t")||"";let paymentId=u.searchParams.get("payment_id")||u.searchParams.get("collection_id")||"";if(!checkoutToken||!paymentId){try{const saved=JSON.parse(localStorage.getItem(STORE_KEY)||"null");if(saved&&Date.now()-Number(saved.createdAt||0)<26*60*60*1000){checkoutToken=checkoutToken||String(saved.checkoutToken||"");paymentId=paymentId||String(saved.paymentId||"");}}catch{}}if(!checkoutToken)return;try{const previous=JSON.parse(localStorage.getItem(STORE_KEY)||"null");localStorage.setItem(STORE_KEY,JSON.stringify({checkoutToken,paymentId,createdAt:previous?.checkoutToken===checkoutToken?previous.createdAt:Date.now()}));}catch{}const error=document.getElementById("checkoutError");if(error)error.hidden=true;try{const data=await verifyCard(checkoutToken,paymentId);if(data.approved){try{localStorage.removeItem(STORE_KEY);}catch{}cleanReturnUrl();return openPlatform(data.accessToken,data.platformUrl);}if(!explicitReturn)return;cleanReturnUrl();window.dispatchEvent(new CustomEvent("jr:card-status",{detail:{...data,checkoutToken,paymentId}}));if(data.fallbackAvailable===true)return;showError("O pagamento com cartão ainda não foi aprovado. Se você já concluiu a compra, aguarde alguns segundos e use “Já paguei / recuperar acesso”.");}catch(err){if(explicitReturn){cleanReturnUrl();showError(err?.message||"Não foi possível confirmar o cartão agora.");}}}
function install(){const form=document.getElementById("checkoutForm");const pixButton=document.getElementById("checkoutSubmit");if(!form||!pixButton)return handleReturn();const heading=document.querySelector(".checkout-head strong");if(heading&&/Pix/i.test(heading.textContent||""))heading.textContent="Pagamento seguro via Pix ou Cartão";let button=document.getElementById("cardCheckoutButton");if(!button){button=document.createElement("button");button.type="button";button.id="cardCheckoutButton";button.className=pixButton.className;button.textContent="PAGAR COM CARTÃO • ATÉ 12X";button.style.cssText="width:100%;margin-top:10px;background:linear-gradient(180deg,#1769aa,#0d4f86);color:#fff;border:0;cursor:pointer";pixButton.insertAdjacentElement("afterend",button);}let note=document.getElementById("cardCheckoutNote");if(!note){note=document.createElement("p");note.id="cardCheckoutNote";note.style.cssText="margin:9px 0 0;text-align:center;font-size:.76rem;line-height:1.45;opacity:.78";note.textContent="Parcelas e eventuais juros são mostrados pelo Mercado Pago antes da confirmação.";button.insertAdjacentElement("afterend",note);}if(button.dataset.jrCardBound!=="1"){button.dataset.jrCardBound="1";button.addEventListener("click",async()=>{const area=selectedArea();const consent=document.getElementById("checkoutConsent");if(!form.reportValidity())return;if(!area)return showError("Escolha sua área de preparação antes de pagar.");if(consent&&!consent.checked)return showError("Confirme seus dados antes de continuar.");const payload={name:document.getElementById("checkoutName")?.value||"",email:document.getElementById("checkoutEmail")?.value||"",cpf:document.getElementById("checkoutCpf")?.value||"",area,variant:selectedVariant(),paymentMethod:"card",checkoutKey:uuid(),termsAccepted:true,termsVersion:"jr-digital-2026-10-01-v1"};button.disabled=true;button.textContent="ABRINDO MERCADO PAGO...";const error=document.getElementById("checkoutError");if(error)error.hidden=true;try{const response=await fetch("/api/checkout",{method:"POST",headers:{"Content-Type":"application/json"},cache:"no-store",body:JSON.stringify(payload)});const data=await response.json().catch(()=>({}));if(!response.ok||!data.checkoutUrl||!data.checkoutToken)throw new Error(data.error||"Não foi possível abrir o cartão.");try{localStorage.setItem(STORE_KEY,JSON.stringify({checkoutToken:data.checkoutToken,paymentId:"",createdAt:Date.now()}));}catch{}window.location.assign(data.checkoutUrl);}catch(err){showError(err?.message||"Pagamento com cartão temporariamente indisponível.");button.disabled=false;button.textContent="PAGAR COM CARTÃO • ATÉ 12X";}});}handleReturn();}
window.addEventListener("focus",handleReturn);
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",install);else install();
})();